# Site settings
title: "BasicCAT — An open source and free computer-aided translation (CAT) tool"
title_zh: "BasicCAT——开源免费的计算机辅助翻译（CAT）软件"
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "xulihang"

# Build settings
kramdown:
  input: GFM
permalink: /:title/

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]

collections:
  zh:
    output: true
    permalink: /:collection/:title/
    

  
