# Site settings
header: BasicCAT
title: "BasicCAT — Computer-Aided Translation (CAT) Tools"
title_zh: "BasicCAT——计算机辅助翻译（CAT）软件"
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
#url: ""
author: "xulihang"

# Build settings
kramdown:
  input: GFM
permalink: /:title/

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 
sitemap: true
plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]

defaults:
  - scope:
      path: "_zh"
    values:
      locale: "zh_CN"
      
collections:
  zh:
    output: true
    permalink: /:collection/:title/
    

  
